site_name: nf-core gitpod run
site_url: http://santorsola-teaching.github.io/nf-core-gitpod-run
repo_url: http://github.com/santorsola-teaching/nf-core-gitpod-run
repo_name: santorsola-teaching/nf-core-gitpod-run

nav:
    - Home: index.md
    - Instructions:
            - de_rstudio.md

theme:
    name: material
    palette:
        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
              icon: material/weather-night
              name: Switch to light mode
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
              icon: material/weather-sunny
              name: Switch to dark mode
    font:
        text: Inter
    features:
        - content.action.edit
        - content.code.annotate
        - content.code.copy
        - navigation.footer
        - navigation.tabs
        - navigation.top
        - navigation.tracking
        - search.share
        - toc.follow
    icon:
        repo: fontawesome/brands/github

markdown_extensions:
    - admonition
    - attr_list
    - md_in_html
    - pymdownx.details
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.snippets:
          base_path: ["."]
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.arithmatex:
          generic: true
    - tables
    - toc:
          title: On this page
          permalink: true

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
